# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Package Tests

on:
    push:
      branches: [ main, master ]
    pull_request:
      branches: [ main, master ]

permissions:
  contents: read

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            python-version: [3.8, 3.9, 3.10, 3.12]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}
            - name: Cache pipenv virtual environment
              uses: actions/cache@v2
              with:
                path: |
                  ~/.local/share/virtualenvs
                  ~/.cache/pipenv
                key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
                restore-keys: |
                  ${{ runner.os }}-pipenv-
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pipenv
                pipenv install --dev
                pip install build
            - name: Build package
              run: |
                pipenv run python -m build
            - name: Run tests
              run: |
                pipenv run pytest